name = "momo-community-low"
main = "src/worker.js"
compatibility_date = "2024-12-15"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "momo-community-low"
database_id = "3c605308-9ee8-4b3a-a010-8ee612a2508e"
